<template>
  <view class="admin-platform">
    <view class="hero"><view><text>ADMIN / OPEN PLATFORM</text><view>开放平台运营中心</view><small>开发者、套餐、活动、佣金、退款与后台任务</small></view><button @click="goUsers">普通用户后台</button></view>
    <scroll-view scroll-x class="tabs"><view v-for="item in tabs" :key="item.key" :class="{active:section===item.key}" @click="switchTab(item.key)">{{item.label}}</view></scroll-view>

    <view v-if="section==='overview'" class="metrics"><view><small>开发者</small><b>{{stats.developers||0}}</b></view><view><small>API 调用</small><b>{{stats.calls||0}}</b></view><view><small>任务 / 异常</small><b>{{stats.tasks||0}} / {{stats.failed_tasks||0}}</b></view></view>

    <template v-if="section==='developers'"><view class="filters"><input v-model.trim="keyword" placeholder="邮箱或名称"/><picker :range="statusLabels" @change="developerStatus=statusValues[$event.detail.value]"><view>{{developerStatus||'全部状态'}}</view></picker><button @click="loadDevelopers">查询</button></view><view class="panel"><view v-if="!developers.length" class="empty">暂无开发者</view><view v-for="item in developers" :key="item.id" class="row"><view><b>{{item.name}}</b><small>{{item.email}} · ID {{item.id}}</small><small>{{item.active_keys}} 个有效 Key · 每分钟 {{item.rate_limit_per_minute}} 次</small></view><view><text class="badge">{{item.status}}</text><button @click="showKeys(item)">查看 Key</button><button v-if="item.status==='active'" class="danger" @click="developerAction(item,'freeze')">冻结</button><button v-else @click="developerAction(item,'unfreeze')">解冻</button></view></view></view></template>

    <template v-if="section==='packages'"><button class="create" @click="editPackage(null)">新建 API 套餐</button><view class="panel"><view v-if="!packages.length" class="empty">尚未创建 API 套餐，默认不会自动上架收费内容。</view><view v-for="item in packages" :key="item.id" class="row"><view><b>{{item.name}}</b><small>{{item.credit_count}} 次 · ¥{{item.price}} · 排序 {{item.sort_order}}</small><small>{{item.description||'无说明'}}</small></view><view><text class="badge">{{item.is_active?'已上架':'草稿/下架'}}</text><button @click="editPackage(item)">编辑</button><button @click="togglePackage(item)">{{item.is_active?'下架':'上架'}}</button></view></view></view></template>

    <template v-if="section==='campaigns'"><button class="create" @click="editCampaign(null)">新建邀请活动</button><view class="panel"><view v-if="!campaigns.length" class="empty">暂无活动；默认模板保存后仍需管理员启用。</view><view v-for="item in campaigns" :key="item.id" class="row"><view><b>{{item.name}}</b><small>佣金 {{Number(item.commission_rate)*100}}% · 双方 {{item.inviter_credit}}/{{item.invitee_credit}} 次</small><small>{{format(item.starts_at)}} 至 {{format(item.ends_at)}}</small></view><view><text class="badge">{{item.is_active?'进行中':'未启用'}}</text><button @click="editCampaign(item)">编辑</button></view></view></view></template>

    <template v-if="section==='referrals'"><view class="filters"><picker :range="rewardStatuses" @change="rewardStatus=rewardStatuses[$event.detail.value]==='全部'?'':rewardStatuses[$event.detail.value]"><view>{{rewardStatus||'全部'}}</view></picker><button @click="loadReferrals">筛选</button></view><view class="panel"><view v-if="!referrals.length" class="empty">暂无佣金记录</view><view v-for="item in referrals" :key="item.id" class="row"><view><b>邀请人 {{item.inviter_id}} → 受邀人 {{item.invitee_id}}</b><small>活动 {{item.campaign_id}} · {{format(item.settle_after)}} 后结算</small></view><view><text class="badge">{{item.status}}</text><b>¥{{item.commission_amount}}</b><button v-if="item.status==='pending'" class="danger" @click="invalidateReward(item)">作废异常奖励</button></view></view></view></template>

    <template v-if="section==='calls'"><view class="filters"><picker :range="callStatuses" @change="callStatus=callStatuses[$event.detail.value]==='全部'?'':callStatuses[$event.detail.value]"><view>{{callStatus||'全部状态'}}</view></picker><button @click="loadCalls">筛选</button></view><view class="panel"><view v-if="!calls.length" class="empty">暂无调用记录</view><view v-for="item in calls" :key="item.id" class="row"><view><b>{{item.endpoint}}</b><small>{{item.request_no}} · 开发者 {{item.developer_id}}</small><small>{{format(item.created_at)}} · {{item.duration_ms||0}} ms</small></view><view><text class="badge">{{item.status}}</text><b>{{item.credit_count}} 次</b></view></view></view></template>

    <template v-if="section==='refunds'"><view class="panel"><view v-if="!refunds.length" class="empty">暂无开发者退款</view><view v-for="item in refunds" :key="item.id" class="row"><view><b>{{item.refund_no}}</b><small>开发者 {{item.developer_id}} · {{item.reason}}</small><small>{{format(item.created_at)}}</small></view><view><text class="badge">{{item.status}}</text><button v-if="item.status==='requested'" @click="reviewRefund(item,true)">批准</button><button v-if="item.status==='requested'" class="danger" @click="reviewRefund(item,false)">驳回</button></view></view></view></template>

    <template v-if="section==='tasks'"><view class="filters"><picker :range="taskTypes" @change="taskType=taskTypes[$event.detail.value]==='全部'?'':taskTypes[$event.detail.value]"><view>{{taskType||'全部类型'}}</view></picker><picker :range="taskStatuses" @change="taskStatus=taskStatuses[$event.detail.value]==='全部'?'':taskStatuses[$event.detail.value]"><view>{{taskStatus||'全部状态'}}</view></picker><button @click="loadTasks">筛选</button></view><view class="panel"><view v-if="!tasks.length" class="empty">暂无任务</view><view v-for="item in tasks" :key="item.task_no" class="row" @click="taskDetail(item)"><view><b>{{item.task_type}} · {{item.owner_type}} {{item.owner_id}}</b><small>{{item.task_no}}</small><small>成功 {{item.success_count}} / 失败 {{item.failure_count}} / 总数 {{item.total_count}}</small></view><view><text class="badge">{{item.status}}</text><button v-if="retryable(item.status)" @click.stop="retry(item)">重试</button></view></view></view></template>
  </view>
</template>
<script>
import { platformAdminApi as api } from '../../api/platform-admin'
import { requireAdminSession, handleAdminAuthError } from '../../utils/auth'
export default{
 data(){return{section:'overview',stats:{},developers:[],packages:[],campaigns:[],referrals:[],refunds:[],tasks:[],calls:[],keyword:'',developerStatus:'',rewardStatus:'',taskType:'',taskStatus:'',callStatus:'',statusLabels:['全部','active','frozen'],statusValues:['','active','frozen'],rewardStatuses:['全部','pending','settled','invalid'],callStatuses:['全部','processing','succeeded','failed'],taskTypes:['全部','batch_naming','knowledge_index'],taskStatuses:['全部','queued','running','succeeded','partial_failed','failed','publish_failed'],tabs:[{key:'overview',label:'概览'},{key:'developers',label:'开发者'},{key:'calls',label:'调用明细'},{key:'packages',label:'API套餐'},{key:'campaigns',label:'活动运营'},{key:'referrals',label:'佣金记录'},{key:'refunds',label:'退款'},{key:'tasks',label:'后台任务'}]}},
 onShow(){if(requireAdminSession())this.loadStats()},methods:{
  switchTab(k){this.section=k;if(k==='overview')this.loadStats();if(k==='developers')this.loadDevelopers();if(k==='calls')this.loadCalls();if(k==='packages')this.loadPackages();if(k==='campaigns')this.loadCampaigns();if(k==='referrals')this.loadReferrals();if(k==='refunds')this.loadRefunds();if(k==='tasks')this.loadTasks()},
  async loadStats(){try{this.stats=await api.stats()}catch(e){this.fail(e)}},async loadDevelopers(){try{this.developers=(await api.developers(this.developerStatus,this.keyword)).items}catch(e){this.fail(e)}},async loadPackages(){try{this.packages=await api.packages()}catch(e){this.fail(e)}},async loadCampaigns(){try{this.campaigns=await api.campaigns()}catch(e){this.fail(e)}},async loadReferrals(){try{this.referrals=await api.referrals(this.rewardStatus)}catch(e){this.fail(e)}},async loadRefunds(){try{this.refunds=await api.refunds()}catch(e){this.fail(e)}},async loadTasks(){try{this.tasks=(await api.tasks(this.taskType,this.taskStatus)).items}catch(e){this.fail(e)}},
  async loadCalls(){try{this.calls=(await api.calls(this.callStatus)).items}catch(e){this.fail(e)}},async showKeys(item){try{const keys=await api.developerKeys(item.id);const active=keys.filter(k=>k.status==='active');const text=keys.length?keys.map(k=>`${k.name} · ${k.key_prefix} · ${k.status}`).join('\n'):'暂无 Key';uni.showModal({title:`${item.name} 的 API Key`,content:text,confirmText:active.length?'吊销一个':'知道了',showCancel:Boolean(active.length),success:({confirm})=>{if(confirm&&active.length)uni.showActionSheet({itemList:active.map(k=>`${k.name} · ${k.key_prefix}`),success:({tapIndex})=>this.revokeKey(active[tapIndex])})}})}catch(e){this.fail(e)}},revokeKey(key){uni.showModal({title:'吊销 API Key',editable:true,placeholderText:'吊销原因（必填）',content:`准确动作：立即停用 ${key.key_prefix}，无法恢复。`,success:async({confirm,content})=>{if(confirm&&content){try{await api.revokeKey(key.id,content);uni.showToast({title:'已吊销',icon:'success'})}catch(e){this.fail(e)}}}})},
  invalidateReward(item){uni.showModal({title:'作废待结算奖励',editable:true,placeholderText:'作废原因（必填）',content:'准确动作：该佣金和双方赠送次数将不再结算，记录及审计仍保留。',success:async({confirm,content})=>{if(confirm&&content){try{await api.invalidateReward(item.id,content);this.loadReferrals()}catch(e){this.fail(e)}}}})},
  developerAction(item,action){uni.showModal({title:action==='freeze'?'冻结开发者':'解冻开发者',editable:true,placeholderText:'操作原因（必填）',content:action==='freeze'?'准确动作：账号登录失效，所有有效 API Key 立即吊销。':'准确动作：恢复登录，但已吊销 Key 不会恢复。',success:async({confirm,content})=>{if(confirm&&content){try{await api[action](item.id,content);this.loadDevelopers()}catch(e){this.fail(e)}}}})},
  editPackage(item){const initial=item?`${item.name}|${item.price}|${item.credit_count}|${item.sort_order}|${item.description||''}`:'标准 API 套餐|99.00|1000|0|';uni.showModal({title:item?'编辑 API 套餐':'新建 API 套餐',editable:true,content:initial,placeholderText:'名称|价格|次数|排序|说明',success:async({confirm,content})=>{if(!confirm)return;const [name,price,credit_count,sort_order,description]=content.split('|');try{await api.savePackage({name,price,credit_count:Number(credit_count),sort_order:Number(sort_order||0),description:description||null,is_active:item?item.is_active:false},item&&item.id);this.loadPackages()}catch(e){this.fail(e)}}})},
  togglePackage(item){uni.showModal({title:item.is_active?'确认下架':'确认上架',content:item.is_active?'新订单将无法购买，已有订单不受影响。':'套餐将立即出现在开发者购买页，请确认价格与次数准确。',success:async({confirm})=>{if(confirm){try{await api.packageStatus(item.id,!item.is_active,'管理员在运营后台调整套餐状态');this.loadPackages()}catch(e){this.fail(e)}}}})},
  editCampaign(item){const now=new Date(),later=new Date(now.getTime()+30*86400000);const value=item?`${item.name}|${Number(item.commission_rate)*100}|${item.inviter_credit}|${item.invitee_credit}|${String(item.starts_at).slice(0,16)}|${String(item.ends_at).slice(0,16)}|${item.is_active?'1':'0'}`:`邀请有礼|10|5|5|${now.toISOString().slice(0,16)}|${later.toISOString().slice(0,16)}|0`;uni.showModal({title:item?'编辑活动':'新建活动',editable:true,content:value,placeholderText:'名称|佣金%|邀请人次数|受邀人次数|开始|结束|启用1',success:async({confirm,content})=>{if(!confirm)return;const [name,rate,inviter,invitee,starts,ends,active]=content.split('|');try{await api.saveCampaign({name,commission_rate:Number(rate)/100,inviter_credit:Number(inviter),invitee_credit:Number(invitee),reward_cap:null,starts_at:starts,ends_at:ends,is_active:active==='1'},item&&item.id);this.loadCampaigns()}catch(e){this.fail(e)}}})},
  reviewRefund(item,approve){uni.showModal({title:approve?'批准开发者退款':'驳回开发者退款',editable:true,placeholderText:'审核说明',content:approve?'准确动作：先向支付宝提交现金退款；成功后回收全部套餐次数并恢复推广余额。':'仅驳回申请，不改变订单、次数或余额。',success:async({confirm,content})=>{if(confirm){try{await api.reviewRefund(item.refund_no,approve,content||null);this.loadRefunds()}catch(e){this.fail(e)}}}})},
  retryable(s){return['failed','partial_failed','publish_failed'].includes(s)},retry(item){uni.showModal({title:'重新入队任务',editable:true,placeholderText:'重试原因（必填）',content:'仅重试失败条目；成功条目不会重复扣费。',success:async({confirm,content})=>{if(confirm&&content){try{await api.retryTask(item.task_no,content);this.loadTasks()}catch(e){this.fail(e)}}}})},taskDetail(item){api.task(item.task_no).then(v=>uni.showModal({title:`任务 ${v.status}`,content:`成功 ${v.success_count}，失败 ${v.failure_count}\n${v.last_error||'暂无错误'}`,showCancel:false})).catch(this.fail)},goUsers(){uni.navigateTo({url:'/pages/admin/users'})},format(v){return v?String(v).replace('T',' ').slice(0,16):'—'},fail(e){if(handleAdminAuthError(e))return;uni.showToast({title:e.message||String(e),icon:'none',duration:3000})}
 }}
</script>
<style scoped>
.admin-platform{min-height:100vh;padding:28rpx;background:#f2f4f7}.hero{display:flex;align-items:center;justify-content:space-between;padding:35rpx;color:#fff;background:linear-gradient(135deg,#121b2b,#31425a);border-radius:28rpx}.hero text{color:#67e0d2;font-size:16rpx;letter-spacing:4rpx}.hero view view{margin-top:12rpx;font-size:36rpx;font-weight:900}.hero small{display:block;margin-top:8rpx;color:#b8c3d0}.hero button{color:#203044;background:#fff;font-size:20rpx}.tabs{margin:20rpx 0;white-space:nowrap}.tabs view{display:inline-block;margin-right:10rpx;padding:17rpx 23rpx;background:#fff;border-radius:14rpx;color:#637083}.tabs .active{color:#fff;background:#33455e;font-weight:800}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:16rpx}.metrics view,.panel,.filters{padding:27rpx;background:#fff;border-radius:22rpx}.metrics small{color:#8994a3}.metrics b{display:block;margin-top:10rpx;font-size:36rpx}.filters{display:flex;gap:12rpx}.filters input,.filters picker{flex:1;padding:18rpx;background:#f0f3f6;border-radius:13rpx}.filters button,.create{color:#fff;background:#33455e}.panel{margin-top:18rpx}.row{display:flex;align-items:center;justify-content:space-between;gap:20rpx;padding:22rpx 0;border-bottom:1rpx solid #edf0f3}.row:last-child{border:0}.row small{display:block;margin-top:5rpx;color:#8994a3;font-size:19rpx}.row button{display:inline-block;margin:7rpx 0 0 8rpx;color:#254f55;background:#e3f3f0;font-size:19rpx}.row .danger{color:#b54358;background:#fff0f3}.badge{display:block;padding:7rpx 11rpx;color:#40546d;background:#e9eef4;border-radius:99rpx;font-size:18rpx}.empty{padding:40rpx;color:#8994a3;text-align:center}.create{margin:0}@media(max-width:600px){.metrics{grid-template-columns:1fr}.hero{align-items:flex-start}.filters{flex-wrap:wrap}}
</style>
