"""add developer platform growth and async tasks

Revision ID: 2700b8ec3ccf
Revises: 7e2a4c9d1b60
Create Date: 2026-08-12 19:17:06.706962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2700b8ec3ccf'
down_revision: Union[str, None] = '7e2a4c9d1b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_package')),
    sa.UniqueConstraint('name', name=op.f('uq_api_package_name'))
    )
    op.create_index(op.f('ix_api_package_is_active'), 'api_package', ['is_active'], unique=False)
    op.create_table('developer_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_account')),
    sa.UniqueConstraint('email', name=op.f('uq_developer_account_email'))
    )
    op.create_index(op.f('ix_developer_account_referral_code'), 'developer_account', ['referral_code'], unique=True)
    op.create_index(op.f('ix_developer_account_status'), 'developer_account', ['status'], unique=False)
    op.create_table('referral_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inviter_credit', sa.Integer(), nullable=False),
    sa.Column('invitee_credit', sa.Integer(), nullable=False),
    sa.Column('reward_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_campaign'))
    )
    op.create_index(op.f('ix_referral_campaign_is_active'), 'referral_campaign', ['is_active'], unique=False)
    op.create_table('api_credit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_api_credit_log_developer_id_developer_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credit_log'))
    )
    op.create_index(op.f('ix_api_credit_log_created_at'), 'api_credit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_credit_log_developer_id'), 'api_credit_log', ['developer_id'], unique=False)
    op.create_index(op.f('ix_api_credit_log_reference'), 'api_credit_log', ['reference'], unique=False)
    op.create_index(op.f('ix_api_credit_log_type'), 'api_credit_log', ['type'], unique=False)
    op.create_table('api_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promotion_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('alipay_trade_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_api_order_developer_id_developer_account')),
    sa.ForeignKeyConstraint(['package_id'], ['api_package.id'], name=op.f('fk_api_order_package_id_api_package')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_order')),
    sa.UniqueConstraint('alipay_trade_no', name=op.f('uq_api_order_alipay_trade_no'))
    )
    op.create_index(op.f('ix_api_order_developer_id'), 'api_order', ['developer_id'], unique=False)
    op.create_index(op.f('ix_api_order_expires_at'), 'api_order', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_order_order_no'), 'api_order', ['order_no'], unique=True)
    op.create_index(op.f('ix_api_order_status'), 'api_order', ['status'], unique=False)
    op.create_table('api_wallet',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('promotion_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_api_wallet_developer_id_developer_account')),
    sa.PrimaryKeyConstraint('developer_id', name=op.f('pk_api_wallet'))
    )
    op.create_table('developer_api_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_developer_api_key_developer_id_developer_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_api_key')),
    sa.UniqueConstraint('key_digest', name=op.f('uq_developer_api_key_key_digest'))
    )
    op.create_index(op.f('ix_developer_api_key_developer_id'), 'developer_api_key', ['developer_id'], unique=False)
    op.create_index(op.f('ix_developer_api_key_key_prefix'), 'developer_api_key', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_developer_api_key_status'), 'developer_api_key', ['status'], unique=False)
    op.create_table('platform_admin_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], name=op.f('fk_platform_admin_audit_admin_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_admin_audit'))
    )
    op.create_index(op.f('ix_platform_admin_audit_action'), 'platform_admin_audit', ['action'], unique=False)
    op.create_index(op.f('ix_platform_admin_audit_admin_user_id'), 'platform_admin_audit', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_platform_admin_audit_target_id'), 'platform_admin_audit', ['target_id'], unique=False)
    op.create_index(op.f('ix_platform_admin_audit_target_type'), 'platform_admin_audit', ['target_type'], unique=False)
    op.create_table('promotion_balance_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_promotion_balance_log_developer_id_developer_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_balance_log'))
    )
    op.create_index(op.f('ix_promotion_balance_log_created_at'), 'promotion_balance_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_promotion_balance_log_developer_id'), 'promotion_balance_log', ['developer_id'], unique=False)
    op.create_index(op.f('ix_promotion_balance_log_reference'), 'promotion_balance_log', ['reference'], unique=False)
    op.create_index(op.f('ix_promotion_balance_log_type'), 'promotion_balance_log', ['type'], unique=False)
    op.create_table('referral_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inviter_credit', sa.Integer(), nullable=False),
    sa.Column('invitee_credit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['referral_campaign.id'], name=op.f('fk_referral_relation_campaign_id_referral_campaign')),
    sa.ForeignKeyConstraint(['invitee_id'], ['developer_account.id'], name=op.f('fk_referral_relation_invitee_id_developer_account')),
    sa.ForeignKeyConstraint(['inviter_id'], ['developer_account.id'], name=op.f('fk_referral_relation_inviter_id_developer_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_relation')),
    sa.UniqueConstraint('invitee_id', name='uq_referral_relation_invitee')
    )
    op.create_index(op.f('ix_referral_relation_invitee_id'), 'referral_relation', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_referral_relation_inviter_id'), 'referral_relation', ['inviter_id'], unique=False)
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.String(length=64), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['developer_api_key.id'], name=op.f('fk_api_call_log_api_key_id_developer_api_key')),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_api_call_log_developer_id_developer_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_call_log')),
    sa.UniqueConstraint('api_key_id', 'idempotency_key', name='uq_api_call_idempotency')
    )
    op.create_index(op.f('ix_api_call_log_api_key_id'), 'api_call_log', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_call_log_created_at'), 'api_call_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_call_log_developer_id'), 'api_call_log', ['developer_id'], unique=False)
    op.create_index(op.f('ix_api_call_log_endpoint'), 'api_call_log', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_call_log_request_no'), 'api_call_log', ['request_no'], unique=True)
    op.create_index(op.f('ix_api_call_log_status'), 'api_call_log', ['status'], unique=False)
    op.create_table('api_refund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('review_note', sa.String(length=200), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_account.id'], name=op.f('fk_api_refund_developer_id_developer_account')),
    sa.ForeignKeyConstraint(['order_id'], ['api_order.id'], name=op.f('fk_api_refund_order_id_api_order')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_api_refund_reviewed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_refund'))
    )
    op.create_index(op.f('ix_api_refund_developer_id'), 'api_refund', ['developer_id'], unique=False)
    op.create_index(op.f('ix_api_refund_order_id'), 'api_refund', ['order_id'], unique=False)
    op.create_index(op.f('ix_api_refund_refund_no'), 'api_refund', ['refund_no'], unique=True)
    op.create_index(op.f('ix_api_refund_status'), 'api_refund', ['status'], unique=False)
    op.create_table('platform_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('reserved_credits', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['developer_api_key.id'], name=op.f('fk_platform_task_api_key_id_developer_api_key')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_task'))
    )
    op.create_index(op.f('ix_platform_task_next_retry_at'), 'platform_task', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_platform_task_owner_id'), 'platform_task', ['owner_id'], unique=False)
    op.create_index(op.f('ix_platform_task_owner_type'), 'platform_task', ['owner_type'], unique=False)
    op.create_index(op.f('ix_platform_task_status'), 'platform_task', ['status'], unique=False)
    op.create_index(op.f('ix_platform_task_task_no'), 'platform_task', ['task_no'], unique=True)
    op.create_index(op.f('ix_platform_task_task_type'), 'platform_task', ['task_type'], unique=False)
    op.create_table('referral_reward',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inviter_credit', sa.Integer(), nullable=False),
    sa.Column('invitee_credit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settle_after', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['api_order.id'], name=op.f('fk_referral_reward_order_id_api_order')),
    sa.ForeignKeyConstraint(['relation_id'], ['referral_relation.id'], name=op.f('fk_referral_reward_relation_id_referral_relation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_reward')),
    sa.UniqueConstraint('order_id', name=op.f('uq_referral_reward_order_id')),
    sa.UniqueConstraint('relation_id', name='uq_referral_reward_relation')
    )
    op.create_index(op.f('ix_referral_reward_relation_id'), 'referral_reward', ['relation_id'], unique=False)
    op.create_index(op.f('ix_referral_reward_settle_after'), 'referral_reward', ['settle_after'], unique=False)
    op.create_index(op.f('ix_referral_reward_status'), 'referral_reward', ['status'], unique=False)
    op.create_table('platform_task_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['platform_task.id'], name=op.f('fk_platform_task_event_task_id_platform_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_task_event'))
    )
    op.create_index(op.f('ix_platform_task_event_task_id'), 'platform_task_event', ['task_id'], unique=False)
    op.create_table('platform_task_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['platform_task.id'], name=op.f('fk_platform_task_item_task_id_platform_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_task_item')),
    sa.UniqueConstraint('task_id', 'item_index', name='uq_platform_task_item_index')
    )
    op.create_index(op.f('ix_platform_task_item_status'), 'platform_task_item', ['status'], unique=False)
    op.create_index(op.f('ix_platform_task_item_task_id'), 'platform_task_item', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_task_item_task_id'), table_name='platform_task_item')
    op.drop_index(op.f('ix_platform_task_item_status'), table_name='platform_task_item')
    op.drop_table('platform_task_item')
    op.drop_index(op.f('ix_platform_task_event_task_id'), table_name='platform_task_event')
    op.drop_table('platform_task_event')
    op.drop_index(op.f('ix_referral_reward_status'), table_name='referral_reward')
    op.drop_index(op.f('ix_referral_reward_settle_after'), table_name='referral_reward')
    op.drop_index(op.f('ix_referral_reward_relation_id'), table_name='referral_reward')
    op.drop_table('referral_reward')
    op.drop_index(op.f('ix_platform_task_task_type'), table_name='platform_task')
    op.drop_index(op.f('ix_platform_task_task_no'), table_name='platform_task')
    op.drop_index(op.f('ix_platform_task_status'), table_name='platform_task')
    op.drop_index(op.f('ix_platform_task_owner_type'), table_name='platform_task')
    op.drop_index(op.f('ix_platform_task_owner_id'), table_name='platform_task')
    op.drop_index(op.f('ix_platform_task_next_retry_at'), table_name='platform_task')
    op.drop_table('platform_task')
    op.drop_index(op.f('ix_api_refund_status'), table_name='api_refund')
    op.drop_index(op.f('ix_api_refund_refund_no'), table_name='api_refund')
    op.drop_index(op.f('ix_api_refund_order_id'), table_name='api_refund')
    op.drop_index(op.f('ix_api_refund_developer_id'), table_name='api_refund')
    op.drop_table('api_refund')
    op.drop_index(op.f('ix_api_call_log_status'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_request_no'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_endpoint'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_developer_id'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_created_at'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_api_key_id'), table_name='api_call_log')
    op.drop_table('api_call_log')
    op.drop_index(op.f('ix_referral_relation_inviter_id'), table_name='referral_relation')
    op.drop_index(op.f('ix_referral_relation_invitee_id'), table_name='referral_relation')
    op.drop_table('referral_relation')
    op.drop_index(op.f('ix_promotion_balance_log_type'), table_name='promotion_balance_log')
    op.drop_index(op.f('ix_promotion_balance_log_reference'), table_name='promotion_balance_log')
    op.drop_index(op.f('ix_promotion_balance_log_developer_id'), table_name='promotion_balance_log')
    op.drop_index(op.f('ix_promotion_balance_log_created_at'), table_name='promotion_balance_log')
    op.drop_table('promotion_balance_log')
    op.drop_index(op.f('ix_platform_admin_audit_target_type'), table_name='platform_admin_audit')
    op.drop_index(op.f('ix_platform_admin_audit_target_id'), table_name='platform_admin_audit')
    op.drop_index(op.f('ix_platform_admin_audit_admin_user_id'), table_name='platform_admin_audit')
    op.drop_index(op.f('ix_platform_admin_audit_action'), table_name='platform_admin_audit')
    op.drop_table('platform_admin_audit')
    op.drop_index(op.f('ix_developer_api_key_status'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_key_prefix'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_developer_id'), table_name='developer_api_key')
    op.drop_table('developer_api_key')
    op.drop_table('api_wallet')
    op.drop_index(op.f('ix_api_order_status'), table_name='api_order')
    op.drop_index(op.f('ix_api_order_order_no'), table_name='api_order')
    op.drop_index(op.f('ix_api_order_expires_at'), table_name='api_order')
    op.drop_index(op.f('ix_api_order_developer_id'), table_name='api_order')
    op.drop_table('api_order')
    op.drop_index(op.f('ix_api_credit_log_type'), table_name='api_credit_log')
    op.drop_index(op.f('ix_api_credit_log_reference'), table_name='api_credit_log')
    op.drop_index(op.f('ix_api_credit_log_developer_id'), table_name='api_credit_log')
    op.drop_index(op.f('ix_api_credit_log_created_at'), table_name='api_credit_log')
    op.drop_table('api_credit_log')
    op.drop_index(op.f('ix_referral_campaign_is_active'), table_name='referral_campaign')
    op.drop_table('referral_campaign')
    op.drop_index(op.f('ix_developer_account_status'), table_name='developer_account')
    op.drop_index(op.f('ix_developer_account_referral_code'), table_name='developer_account')
    op.drop_table('developer_account')
    op.drop_index(op.f('ix_api_package_is_active'), table_name='api_package')
    op.drop_table('api_package')
    # ### end Alembic commands ###
