"""change

Revision ID: 6a618da337cc
Revises: 23bd3d9f69f2
Create Date: 2026-07-23 16:42:47.429367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a618da337cc'
down_revision: Union[str, None] = '23bd3d9f69f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_package_name'), 'package', ['name'])
    op.alter_column('user_order', 'alipay_trade_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_order', 'alipay_trade_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('uq_package_name'), 'package', type_='unique')
    # ### end Alembic commands ###
